# Introduction of Numpy

#### NUMPY

This is a fundamental Package for scientific computing for manipulation of multi-dimensional arrays and matrices.  It is particularly useful for linear algebra, Fourier transform, random number simulation etc 

Matrices are rectangular array of numbers, symbols and expressions arranged in rows and columns. The numbers, symbols or expressions in the matrix are called its entries or its elements. The horizontal and vertical lines of entries in a matrix are called rows and columns, respectively. Its operations inclue addition, subtraction, multiplication



#### 1. Importing Numpy

The first step is to import numpy library into the active notebook

In [1]:
import numpy

To shorten the length of any library, a better alternative is to instantiate the library with a shorter name, as in

In [2]:
import numpy as np

With this, each time numpy is required on this active notebook, **np** will be used instead

#### 2. Creating Numpy Array

The [np.array](https://docs.scipy.org/doc/numpy/reference/generated/numpy.array.html) function is used to create an array

In [3]:
#creating a 1 dimensional array

x = np.array([1, 2, 3, 4, 5])
y = np.array([9, 10]) 
print(x)
print('The shape of X is', x.shape)

print(y)
print('The shape of Y is', y.shape)

[1 2 3 4 5]
The shape of X is (5,)
[ 9 10]
The shape of Y is (2,)


The [shape](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.shape.html) property is usually used to get the current shape of an array

In [4]:
# Creating a 2D arrays  
z = np.array([[1, 2], [3, 4], [5, 6]]) 

print(z)
print('The shape of Z is', z.shape)

[[1 2]
 [3 4]
 [5 6]]
The shape of Z is (3, 2)


#### 3. Numpy Functions

Numpy has built-in functions for creating arrays and manipulating. These includes:

- np.arange 

- np.reshape

- np.zeros 

>The dimensions (no of rows and column) are passed as parameters to the function.

In [5]:
#arange is Used to create arrays with values in a specified range.

A = np.arange(25)
print(A)
print(A.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
(25,)


In [6]:
#To change the shape of an array

B = A.reshape(25,1)

print (B)
print ("The shape of 1D array X = ", B.shape)

[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]
 [24]]
The shape of 1D array X =  (25, 1)


In [7]:
C = B.reshape(5,5)

print ( C)
print ("The shape of array C = ", C.shape)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
The shape of array C =  (5, 5)


> Note: Before a reshape function will run sucessful, the multiplication of the two parameter supply to the function must be equal with multiplication of the shape of the orginal array you want to reshape.

For example: The shape of variable B is (25, 1) therefore 25 * 1 = 25

The two parameter supply to the reshape function is (5, 5), 5 * 5 = 25
              

In [8]:
#zeros is used to create an array filled with zeros. 

np_Zeros = np.zeros((2,3))

np_Zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

#### 4. Accessing elements of Numpy array

To access an element in a two-dimensional array, you need to specify an index for both the row and the column.

In [9]:
D = np.array([[5, 7, 8],[3, 5, 9]])

In [10]:
D

array([[5, 7, 8],
       [3, 5, 9]])

In [11]:
# note that for array numbering in numpy, it that from zero
#Row 1, column 0 gives a scalar value
D[1,0]

3

In [12]:
#Row 1, column 1
D[1,1]

5

In [13]:
#Row 1, column 2
D[1,2]

9

In [14]:
# Slicing is also possible in numpy
D[0:1, :]

array([[5, 7, 8]])

#### 5. Numpy array math operations

In [15]:
x = np.array([[1,2,3],[4,5,6]])
y = np.array([[2,2,2],[3,3,3]])
z = np.array([1,2,3])

In [16]:
#Transpose a matrix

x.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [17]:
#Elementwise addittion

print (x+y)
print (np.add(x,y))

[[3 4 5]
 [7 8 9]]
[[3 4 5]
 [7 8 9]]


In [18]:
#Elementwise Subtraction

print (x-y)
print (np.subtract(x,y))

[[-1  0  1]
 [ 1  2  3]]
[[-1  0  1]
 [ 1  2  3]]


In [19]:
#Elementwise Multiplication

print (x*z)
print (np.multiply(x,z))

[[ 1  4  9]
 [ 4 10 18]]
[[ 1  4  9]
 [ 4 10 18]]


In [20]:
# Inner product of vectors 
print(np.dot(x, z)) 

[14 32]
